//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18052
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chiffon.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chiffon.Resources.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XXX.
        /// </summary>
        public static string Designer_Index_Description {
            get {
                return ResourceManager.GetString("Designer_Index_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XXX.
        /// </summary>
        public static string Designer_Index_Title {
            get {
                return ResourceManager.GetString("Designer_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XXX.
        /// </summary>
        public static string Designer_Pattern_Description {
            get {
                return ResourceManager.GetString("Designer_Pattern_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XXX.
        /// </summary>
        public static string Designer_Pattern_Title {
            get {
                return ResourceManager.GetString("Designer_Pattern_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XXX.
        /// </summary>
        public static string Home_About_Description {
            get {
                return ResourceManager.GetString("Home_About_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XXX.
        /// </summary>
        public static string Home_About_Title {
            get {
                return ResourceManager.GetString("Home_About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XXX.
        /// </summary>
        public static string Home_Contact_Description {
            get {
                return ResourceManager.GetString("Home_Contact_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XXX.
        /// </summary>
        public static string Home_Contact_Title {
            get {
                return ResourceManager.GetString("Home_Contact_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XXX.
        /// </summary>
        public static string Home_Index_Description {
            get {
                return ResourceManager.GetString("Home_Index_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XXX.
        /// </summary>
        public static string Home_Index_Title {
            get {
                return ResourceManager.GetString("Home_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XXX.
        /// </summary>
        public static string Home_Newsletter_Description {
            get {
                return ResourceManager.GetString("Home_Newsletter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XXX.
        /// </summary>
        public static string Home_Newsletter_Title {
            get {
                return ResourceManager.GetString("Home_Newsletter_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pour quel motif, Simone ? Collectif de designers textiles..
        /// </summary>
        public static string MetaDescription {
            get {
                return ResourceManager.GetString("MetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Design textile.
        /// </summary>
        public static string MetaKeywords {
            get {
                return ResourceManager.GetString("MetaKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Motif textile par {1}, référence n°{0}.
        /// </summary>
        public static string PatternDescriptionFormat {
            get {
                return ResourceManager.GetString("PatternDescriptionFormat", resourceCulture);
            }
        }
    }
}
