//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18052
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chiffon.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VR() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chiffon.Resources.VR", typeof(VR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tous.
        /// </summary>
        public static string Category_All {
            get {
                return ResourceManager.GetString("Category_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pour visualiser notre catalogue,&lt;span class=break /&gt; entrez le mot de passe qui vous a été attribué..
        /// </summary>
        public static string ContactLogin_DescriptionHtml {
            get {
                return ResourceManager.GetString("ContactLogin_DescriptionHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Agence.
        /// </summary>
        public static string ContactRegister_CompanyName {
            get {
                return ResourceManager.GetString("ContactRegister_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pour obtenir votre mot de passe,&lt;span class=break /&gt; veuillez remplir le formulaire..
        /// </summary>
        public static string ContactRegister_DescriptionHtml {
            get {
                return ResourceManager.GetString("ContactRegister_DescriptionHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        public static string ContactRegister_EmailAddress {
            get {
                return ResourceManager.GetString("ContactRegister_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prénom.
        /// </summary>
        public static string ContactRegister_Firstname {
            get {
                return ResourceManager.GetString("ContactRegister_Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bonjour,.
        /// </summary>
        public static string ContactRegister_Hello {
            get {
                return ResourceManager.GetString("ContactRegister_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        public static string ContactRegister_Lastname {
            get {
                return ResourceManager.GetString("ContactRegister_Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à J&apos;ai déjà un mot de passe.
        /// </summary>
        public static string ContactRegister_Login {
            get {
                return ResourceManager.GetString("ContactRegister_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sujet.
        /// </summary>
        public static string ContactRegister_Message {
            get {
                return ResourceManager.GetString("ContactRegister_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe.
        /// </summary>
        public static string ContactRegister_Password {
            get {
                return ResourceManager.GetString("ContactRegister_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Demander un mot de passe.
        /// </summary>
        public static string ContactRegister_RequestPassword {
            get {
                return ResourceManager.GetString("ContactRegister_RequestPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Envoyer.
        /// </summary>
        public static string ContactRegister_Submit {
            get {
                return ResourceManager.GetString("ContactRegister_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valider.
        /// </summary>
        public static string ContactRegister_Validate {
            get {
                return ResourceManager.GetString("ContactRegister_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez renseigner tous les champs entourés en rouge..
        /// </summary>
        public static string ContactRegister_ValidationMessage {
            get {
                return ResourceManager.GetString("ContactRegister_ValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Je demande un mot de passe.
        /// </summary>
        public static string HomeAbout_PasswordRequest {
            get {
                return ResourceManager.GetString("HomeAbout_PasswordRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ou un membre du collectif ?.
        /// </summary>
        public static string HomeContact_TitleEnd {
            get {
                return ResourceManager.GetString("HomeContact_TitleEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous souhaitez contactez le collectif ?.
        /// </summary>
        public static string HomeContact_TitleStart {
            get {
                return ResourceManager.GetString("HomeContact_TitleStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à © Pour quel motif, Simone ? 2013..
        /// </summary>
        public static string Layout_Copyright {
            get {
                return ResourceManager.GetString("Layout_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Conformément aux lois régissants les droits d&apos;auteurs, les éléments du site (motifs, illustrations et maquette) pourquelmotifsimone ? sont la propriété exclusive de leurs auteurs. En conséquence toute image utilisée sans le consentement de l&apos;auteur pourra donc faire l&apos;objet de poursuite.&lt;span class=break /&gt;Conception graphique : Viviane Devaux. Mise en scène : chtoucas@narvalo.org..
        /// </summary>
        public static string Layout_DisclaimerHtml {
            get {
                return ResourceManager.GetString("Layout_DisclaimerHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Info.
        /// </summary>
        public static string Layout_Nav_About {
            get {
                return ResourceManager.GetString("Layout_Nav_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contact.
        /// </summary>
        public static string Layout_Nav_Contact {
            get {
                return ResourceManager.GetString("Layout_Nav_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accueil.
        /// </summary>
        public static string Layout_Nav_Home {
            get {
                return ResourceManager.GetString("Layout_Nav_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Newsletter.
        /// </summary>
        public static string Layout_Nav_Newsletter {
            get {
                return ResourceManager.GetString("Layout_Nav_Newsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suiv.
        /// </summary>
        public static string Pager_Next {
            get {
                return ResourceManager.GetString("Pager_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à sur.
        /// </summary>
        public static string Pager_Of {
            get {
                return ResourceManager.GetString("Pager_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Préc.
        /// </summary>
        public static string Pager_Previous {
            get {
                return ResourceManager.GetString("Pager_Previous", resourceCulture);
            }
        }
    }
}
