//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chiffon.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chiffon.Resources.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connectez-vous pour consulter le catalogue..
        /// </summary>
        public static string Account_Login_Description {
            get {
                return ResourceManager.GetString("Account_Login_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre connexion.
        /// </summary>
        public static string Account_Login_MainHeading {
            get {
                return ResourceManager.GetString("Account_Login_MainHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion - Pour quel motif, Simone ?.
        /// </summary>
        public static string Account_Login_Title {
            get {
                return ResourceManager.GetString("Account_Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La newsletter des Simone ?.
        /// </summary>
        public static string Account_Newsletter_Description {
            get {
                return ResourceManager.GetString("Account_Newsletter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Abonnez-vous à la newsletter.
        /// </summary>
        public static string Account_Newsletter_MainHeading {
            get {
                return ResourceManager.GetString("Account_Newsletter_MainHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Newsletter - Pour quel motif, Simone ?.
        /// </summary>
        public static string Account_Newsletter_Title {
            get {
                return ResourceManager.GetString("Account_Newsletter_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créez votre compte pour consulter le catalogue..
        /// </summary>
        public static string Account_Register_Description {
            get {
                return ResourceManager.GetString("Account_Register_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inscrivez-vous.
        /// </summary>
        public static string Account_Register_MainHeading {
            get {
                return ResourceManager.GetString("Account_Register_MainHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrement - Pour quel motif, Simone ?.
        /// </summary>
        public static string Account_Register_Title {
            get {
                return ResourceManager.GetString("Account_Register_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inscription terminée.
        /// </summary>
        public static string Account_RegisterSuccess_MainHeading {
            get {
                return ResourceManager.GetString("Account_RegisterSuccess_MainHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pour quel motif, Simone ? Collectif de designers textile..
        /// </summary>
        public static string DefaultDescription {
            get {
                return ResourceManager.GetString("DefaultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Design textile, Illustrations, Motifs.
        /// </summary>
        public static string DefaultKeywords {
            get {
                return ResourceManager.GetString("DefaultKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pour quel motif, Simone ?.
        /// </summary>
        public static string DefaultTitle {
            get {
                return ResourceManager.GetString("DefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les motifs textiles de {0} dans la catégorie {1}..
        /// </summary>
        public static string Designer_Category_DescriptionFormat {
            get {
                return ResourceManager.GetString("Designer_Category_DescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;{0}&quot; par {1} - Pour quel motif, Simone ?.
        /// </summary>
        public static string Designer_Category_TitleFormat {
            get {
                return ResourceManager.GetString("Designer_Category_TitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Motifs textiles par {0}..
        /// </summary>
        public static string Designer_Index_DescriptionFormat {
            get {
                return ResourceManager.GetString("Designer_Index_DescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} - Pour quel motif, Simone ?.
        /// </summary>
        public static string Designer_Index_TitleFormat {
            get {
                return ResourceManager.GetString("Designer_Index_TitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Motif textile n°{0} par {1} dans la catégorie {2}..
        /// </summary>
        public static string Designer_Pattern_DescriptionFormat {
            get {
                return ResourceManager.GetString("Designer_Pattern_DescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} ({1}).
        /// </summary>
        public static string Designer_Pattern_MainHeadingFormat {
            get {
                return ResourceManager.GetString("Designer_Pattern_MainHeadingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Motif textile n°{0} par {1} - Pour quel motif, Simone ?.
        /// </summary>
        public static string Designer_Pattern_TitleFormat {
            get {
                return ResourceManager.GetString("Designer_Pattern_TitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à À propos du collectif de designers textile Pour quel motif, Simone ?.
        /// </summary>
        public static string Home_About_Description {
            get {
                return ResourceManager.GetString("Home_About_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à À propos.
        /// </summary>
        public static string Home_About_MainHeading {
            get {
                return ResourceManager.GetString("Home_About_MainHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à À propos - Pour quel motif, Simone ?.
        /// </summary>
        public static string Home_About_Title {
            get {
                return ResourceManager.GetString("Home_About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contactez le collectif ou une des Simone..
        /// </summary>
        public static string Home_Contact_Description {
            get {
                return ResourceManager.GetString("Home_Contact_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre message.
        /// </summary>
        public static string Home_Contact_MainHeading {
            get {
                return ResourceManager.GetString("Home_Contact_MainHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contact - Pour quel motif, Simone ?.
        /// </summary>
        public static string Home_Contact_Title {
            get {
                return ResourceManager.GetString("Home_Contact_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre message.
        /// </summary>
        public static string Home_ContactSuccess_MainHeading {
            get {
                return ResourceManager.GetString("Home_ContactSuccess_MainHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pour quel motif, Simone ? Collectif de designers textile..
        /// </summary>
        public static string Home_Index_Description {
            get {
                return ResourceManager.GetString("Home_Index_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Découvrez maintenant notre catalogue.
        /// </summary>
        public static string Home_Index_MainHeading {
            get {
                return ResourceManager.GetString("Home_Index_MainHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pour quel motif, Simone ?.
        /// </summary>
        public static string Home_Index_Title {
            get {
                return ResourceManager.GetString("Home_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Motif textile n°{0} par {1}.
        /// </summary>
        public static string PatternDescriptionFormat {
            get {
                return ResourceManager.GetString("PatternDescriptionFormat", resourceCulture);
            }
        }
    }
}
