//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chiffon.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chiffon.Resources.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectez-vous pour consulter le catalogue..
        /// </summary>
        public static string Account_Login_Description {
            get {
                return ResourceManager.GetString("Account_Login_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre connexion.
        /// </summary>
        public static string Account_Login_MainHeading {
            get {
                return ResourceManager.GetString("Account_Login_MainHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion - Pour quel motif, Simone ?.
        /// </summary>
        public static string Account_Login_Title {
            get {
                return ResourceManager.GetString("Account_Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La newsletter des Simone ?.
        /// </summary>
        public static string Account_Newsletter_Description {
            get {
                return ResourceManager.GetString("Account_Newsletter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abonnez-vous à la newsletter.
        /// </summary>
        public static string Account_Newsletter_MainHeading {
            get {
                return ResourceManager.GetString("Account_Newsletter_MainHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletter - Pour quel motif, Simone ?.
        /// </summary>
        public static string Account_Newsletter_Title {
            get {
                return ResourceManager.GetString("Account_Newsletter_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créez votre compte pour consulter le catalogue..
        /// </summary>
        public static string Account_Register_Description {
            get {
                return ResourceManager.GetString("Account_Register_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscrivez-vous.
        /// </summary>
        public static string Account_Register_MainHeading {
            get {
                return ResourceManager.GetString("Account_Register_MainHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrement - Pour quel motif, Simone ?.
        /// </summary>
        public static string Account_Register_Title {
            get {
                return ResourceManager.GetString("Account_Register_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscription terminée.
        /// </summary>
        public static string Account_RegisterSuccess_MainHeading {
            get {
                return ResourceManager.GetString("Account_RegisterSuccess_MainHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pour quel motif, Simone ? Collectif de designers textile..
        /// </summary>
        public static string DefaultDescription {
            get {
                return ResourceManager.GetString("DefaultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design textile, Illustrations, Motifs.
        /// </summary>
        public static string DefaultKeywords {
            get {
                return ResourceManager.GetString("DefaultKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pour quel motif, Simone ?.
        /// </summary>
        public static string DefaultTitle {
            get {
                return ResourceManager.GetString("DefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les motifs textiles de {0} dans la catégorie {1}..
        /// </summary>
        public static string Designer_Category_DescriptionFormat {
            get {
                return ResourceManager.GetString("Designer_Category_DescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; par {1} - Pour quel motif, Simone ?.
        /// </summary>
        public static string Designer_Category_TitleFormat {
            get {
                return ResourceManager.GetString("Designer_Category_TitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motifs textiles par {0}..
        /// </summary>
        public static string Designer_Index_DescriptionFormat {
            get {
                return ResourceManager.GetString("Designer_Index_DescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Pour quel motif, Simone ?.
        /// </summary>
        public static string Designer_Index_TitleFormat {
            get {
                return ResourceManager.GetString("Designer_Index_TitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motif textile n°{0} par {1} dans la catégorie {2}..
        /// </summary>
        public static string Designer_Pattern_DescriptionFormat {
            get {
                return ResourceManager.GetString("Designer_Pattern_DescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        public static string Designer_Pattern_MainHeadingFormat {
            get {
                return ResourceManager.GetString("Designer_Pattern_MainHeadingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motif textile n°{0} par {1} - Pour quel motif, Simone ?.
        /// </summary>
        public static string Designer_Pattern_TitleFormat {
            get {
                return ResourceManager.GetString("Designer_Pattern_TitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À propos du collectif de designers textile Pour quel motif, Simone ?.
        /// </summary>
        public static string Home_About_Description {
            get {
                return ResourceManager.GetString("Home_About_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À propos.
        /// </summary>
        public static string Home_About_MainHeading {
            get {
                return ResourceManager.GetString("Home_About_MainHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À propos - Pour quel motif, Simone ?.
        /// </summary>
        public static string Home_About_Title {
            get {
                return ResourceManager.GetString("Home_About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactez le collectif ou une des Simone..
        /// </summary>
        public static string Home_Contact_Description {
            get {
                return ResourceManager.GetString("Home_Contact_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre message.
        /// </summary>
        public static string Home_Contact_MainHeading {
            get {
                return ResourceManager.GetString("Home_Contact_MainHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact - Pour quel motif, Simone ?.
        /// </summary>
        public static string Home_Contact_Title {
            get {
                return ResourceManager.GetString("Home_Contact_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre message.
        /// </summary>
        public static string Home_ContactSuccess_MainHeading {
            get {
                return ResourceManager.GetString("Home_ContactSuccess_MainHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pour quel motif, Simone ? Collectif de designers textile..
        /// </summary>
        public static string Home_Index_Description {
            get {
                return ResourceManager.GetString("Home_Index_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Découvrez maintenant notre catalogue.
        /// </summary>
        public static string Home_Index_MainHeading {
            get {
                return ResourceManager.GetString("Home_Index_MainHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pour quel motif, Simone ?.
        /// </summary>
        public static string Home_Index_Title {
            get {
                return ResourceManager.GetString("Home_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motif textile n°{0} par {1}.
        /// </summary>
        public static string PatternDescriptionFormat {
            get {
                return ResourceManager.GetString("PatternDescriptionFormat", resourceCulture);
            }
        }
    }
}
