//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18408
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chiffon.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VR() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chiffon.Resources.VR", typeof(VR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe.
        /// </summary>
        public static string Account_Login_Password {
            get {
                return ResourceManager.GetString("Account_Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Demander un mot de passe.
        /// </summary>
        public static string Account_Login_RequestPassword {
            get {
                return ResourceManager.GetString("Account_Login_RequestPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valider.
        /// </summary>
        public static string Account_Login_Validate {
            get {
                return ResourceManager.GetString("Account_Login_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Feuilleter le catalogue.
        /// </summary>
        public static string Account_PostRegister_BrowseGallery {
            get {
                return ResourceManager.GetString("Account_PostRegister_BrowseGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à À bientôt !.
        /// </summary>
        public static string Account_PostRegister_Byebye {
            get {
                return ResourceManager.GetString("Account_PostRegister_Byebye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les Simone ont le plaisir de vous informer que votre demande a bien été prise en compte..
        /// </summary>
        public static string Account_PostRegister_Success {
            get {
                return ResourceManager.GetString("Account_PostRegister_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Agence *.
        /// </summary>
        public static string Account_Register_CompanyName {
            get {
                return ResourceManager.GetString("Account_Register_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email *.
        /// </summary>
        public static string Account_Register_EmailAddress {
            get {
                return ResourceManager.GetString("Account_Register_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prénom *.
        /// </summary>
        public static string Account_Register_Firstname {
            get {
                return ResourceManager.GetString("Account_Register_Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom *.
        /// </summary>
        public static string Account_Register_Lastname {
            get {
                return ResourceManager.GetString("Account_Register_Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à J&apos;ai déjà un mot de passe.
        /// </summary>
        public static string Account_Register_Login {
            get {
                return ResourceManager.GetString("Account_Register_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à * Ces champs sont obligatoires.
        /// </summary>
        public static string Account_Register_MandatoryFields {
            get {
                return ResourceManager.GetString("Account_Register_MandatoryFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sujet.
        /// </summary>
        public static string Account_Register_Message {
            get {
                return ResourceManager.GetString("Account_Register_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Oui, je veux recevoir la gazette mensuelle des Simone !.
        /// </summary>
        public static string Account_Register_Newsletter {
            get {
                return ResourceManager.GetString("Account_Register_Newsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe.
        /// </summary>
        public static string Account_Register_Password {
            get {
                return ResourceManager.GetString("Account_Register_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Je m&apos;inscris.
        /// </summary>
        public static string Account_Register_Submit {
            get {
                return ResourceManager.GetString("Account_Register_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez vérifier les champs entourés en rouge..
        /// </summary>
        public static string Account_Register_ValidationMessage {
            get {
                return ResourceManager.GetString("Account_Register_ValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bienvenue,.
        /// </summary>
        public static string Account_Register_Welcome {
            get {
                return ResourceManager.GetString("Account_Register_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tous.
        /// </summary>
        public static string Category_All {
            get {
                return ResourceManager.GetString("Category_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nous contacter.
        /// </summary>
        public static string Home_About_ContactUs {
            get {
                return ResourceManager.GetString("Home_About_ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Je demande un mot de passe.
        /// </summary>
        public static string Home_About_PasswordRequest {
            get {
                return ResourceManager.GetString("Home_About_PasswordRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à © Pour quel motif, Simone ? 2013..
        /// </summary>
        public static string Layout_Copyright {
            get {
                return ResourceManager.GetString("Layout_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Info.
        /// </summary>
        public static string Layout_Nav_About {
            get {
                return ResourceManager.GetString("Layout_Nav_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contact.
        /// </summary>
        public static string Layout_Nav_Contact {
            get {
                return ResourceManager.GetString("Layout_Nav_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accueil.
        /// </summary>
        public static string Layout_Nav_Home {
            get {
                return ResourceManager.GetString("Layout_Nav_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Se connecter.
        /// </summary>
        public static string Layout_Nav_Login {
            get {
                return ResourceManager.GetString("Layout_Nav_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Newsletter.
        /// </summary>
        public static string Layout_Nav_Newsletter {
            get {
                return ResourceManager.GetString("Layout_Nav_Newsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suiv.
        /// </summary>
        public static string Pager_Next {
            get {
                return ResourceManager.GetString("Pager_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à sur.
        /// </summary>
        public static string Pager_Of {
            get {
                return ResourceManager.GetString("Pager_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Préc.
        /// </summary>
        public static string Pager_Previous {
            get {
                return ResourceManager.GetString("Pager_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réf.
        /// </summary>
        public static string Pattern_Ref {
            get {
                return ResourceManager.GetString("Pattern_Ref", resourceCulture);
            }
        }
    }
}
