//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chiffon.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chiffon.Resources.VR", typeof(VR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre email *.
        /// </summary>
        public static string Account_Login_Email {
            get {
                return ResourceManager.GetString("Account_Login_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saisissez vos identifiants de connexion pour accéder au catalogue.
        /// </summary>
        public static string Account_Login_Heading {
            get {
                return ResourceManager.GetString("Account_Login_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Ces champs sont obligatoires.
        /// </summary>
        public static string Account_Login_MandatoryFields {
            get {
                return ResourceManager.GetString("Account_Login_MandatoryFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous êtes un nouvel utilisateur.
        /// </summary>
        public static string Account_Login_NewUser {
            get {
                return ResourceManager.GetString("Account_Login_NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre mot de passe *.
        /// </summary>
        public static string Account_Login_Password {
            get {
                return ResourceManager.GetString("Account_Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je crée un compte.
        /// </summary>
        public static string Account_Login_Register {
            get {
                return ResourceManager.GetString("Account_Login_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectez-vous.
        /// </summary>
        public static string Account_Login_Submit {
            get {
                return ResourceManager.GetString("Account_Login_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déjà inscrit(e) ?.
        /// </summary>
        public static string Account_Register_AlreadyRegistered {
            get {
                return ResourceManager.GetString("Account_Register_AlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre agence *.
        /// </summary>
        public static string Account_Register_CompanyName {
            get {
                return ResourceManager.GetString("Account_Register_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectez-vous.
        /// </summary>
        public static string Account_Register_Connect {
            get {
                return ResourceManager.GetString("Account_Register_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre email *.
        /// </summary>
        public static string Account_Register_Email {
            get {
                return ResourceManager.GetString("Account_Register_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre prénom *.
        /// </summary>
        public static string Account_Register_Firstname {
            get {
                return ResourceManager.GetString("Account_Register_Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remplissez le formulaire ci-dessous pour feuilleter le catalogue.
        /// </summary>
        public static string Account_Register_Heading {
            get {
                return ResourceManager.GetString("Account_Register_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre nom *.
        /// </summary>
        public static string Account_Register_Lastname {
            get {
                return ResourceManager.GetString("Account_Register_Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J&apos;ai déjà un mot de passe.
        /// </summary>
        public static string Account_Register_Login {
            get {
                return ResourceManager.GetString("Account_Register_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Ces champs sont obligatoires.
        /// </summary>
        public static string Account_Register_MandatoryFields {
            get {
                return ResourceManager.GetString("Account_Register_MandatoryFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sujet.
        /// </summary>
        public static string Account_Register_Message {
            get {
                return ResourceManager.GetString("Account_Register_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui, je veux recevoir la gazette mensuelle des Simone !.
        /// </summary>
        public static string Account_Register_Newsletter {
            get {
                return ResourceManager.GetString("Account_Register_Newsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe.
        /// </summary>
        public static string Account_Register_Password {
            get {
                return ResourceManager.GetString("Account_Register_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validez votre inscription.
        /// </summary>
        public static string Account_Register_Submit {
            get {
                return ResourceManager.GetString("Account_Register_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez vérifier les champs entourés en rouge..
        /// </summary>
        public static string Account_Register_ValidationMessage {
            get {
                return ResourceManager.GetString("Account_Register_ValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je crée un compte.
        /// </summary>
        public static string Account_RegisterFailure_Register {
            get {
                return ResourceManager.GetString("Account_RegisterFailure_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feuilleter le catalogue.
        /// </summary>
        public static string Account_RegisterSuccess_BrowseGallery {
            get {
                return ResourceManager.GetString("Account_RegisterSuccess_BrowseGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous recevrez très prochainement vos identifiants dans votre boîte mail.
        /// </summary>
        public static string Account_RegisterSuccess_EmailSent {
            get {
                return ResourceManager.GetString("Account_RegisterSuccess_EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre demande a bien été prise en compte.
        /// </summary>
        public static string Account_RegisterSuccess_Heading {
            get {
                return ResourceManager.GetString("Account_RegisterSuccess_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous.
        /// </summary>
        public static string Category_All {
            get {
                return ResourceManager.GetString("Category_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les Simone sont confuses mais le site n&apos;est pas en mesure de répondre à votre demande..
        /// </summary>
        public static string Error_BadRequest {
            get {
                return ResourceManager.GetString("Error_BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les Simone sont confuses mais le site est dans les choux..
        /// </summary>
        public static string Error_DefaultMessage {
            get {
                return ResourceManager.GetString("Error_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accueil.
        /// </summary>
        public static string Error_Home {
            get {
                return ResourceManager.GetString("Error_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les Simone sont confuses mais le site est dans les choux..
        /// </summary>
        public static string Error_InternalServerError {
            get {
                return ResourceManager.GetString("Error_InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les Simone sont confuses mais la page demandée n&apos;existe pas..
        /// </summary>
        public static string Error_NotFound {
            get {
                return ResourceManager.GetString("Error_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les Simone sont confuses mais le site est en cours de maintenance..
        /// </summary>
        public static string Error_ServiceUnavailable {
            get {
                return ResourceManager.GetString("Error_ServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre email *.
        /// </summary>
        public static string Home_Contact_Email {
            get {
                return ResourceManager.GetString("Home_Contact_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre message *.
        /// </summary>
        public static string Home_Contact_Message {
            get {
                return ResourceManager.GetString("Home_Contact_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre nom *.
        /// </summary>
        public static string Home_Contact_Name {
            get {
                return ResourceManager.GetString("Home_Contact_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envoyez le message.
        /// </summary>
        public static string Home_Contact_Submit {
            get {
                return ResourceManager.GetString("Home_Contact_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nous vous répondrons dans les meilleurs délais.
        /// </summary>
        public static string Home_ContactConfirmation_AnsweringSoon {
            get {
                return ResourceManager.GetString("Home_ContactConfirmation_AnsweringSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feuilleter le catalogue.
        /// </summary>
        public static string Home_ContactConfirmation_BrowseGallery {
            get {
                return ResourceManager.GetString("Home_ContactConfirmation_BrowseGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre message a bien été envoyé.
        /// </summary>
        public static string Home_ContactConfirmation_Heading {
            get {
                return ResourceManager.GetString("Home_ContactConfirmation_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voir toute la collection &gt;.
        /// </summary>
        public static string Home_Index_PreviewWatermark {
            get {
                return ResourceManager.GetString("Home_Index_PreviewWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Layout_Nav_About {
            get {
                return ResourceManager.GetString("Layout_Nav_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Layout_Nav_Contact {
            get {
                return ResourceManager.GetString("Layout_Nav_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accueil.
        /// </summary>
        public static string Layout_Nav_Home {
            get {
                return ResourceManager.GetString("Layout_Nav_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se connecter.
        /// </summary>
        public static string Layout_Nav_Login {
            get {
                return ResourceManager.GetString("Layout_Nav_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se déconnecter.
        /// </summary>
        public static string Layout_Nav_Logout {
            get {
                return ResourceManager.GetString("Layout_Nav_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletter.
        /// </summary>
        public static string Layout_Nav_Newsletter {
            get {
                return ResourceManager.GetString("Layout_Nav_Newsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&apos;inscrire.
        /// </summary>
        public static string Layout_Nav_Register {
            get {
                return ResourceManager.GetString("Layout_Nav_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suiv.
        /// </summary>
        public static string Pager_Next {
            get {
                return ResourceManager.GetString("Pager_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sur.
        /// </summary>
        public static string Pager_Of {
            get {
                return ResourceManager.GetString("Pager_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Préc.
        /// </summary>
        public static string Pager_Previous {
            get {
                return ResourceManager.GetString("Pager_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réf.
        /// </summary>
        public static string Pattern_Ref {
            get {
                return ResourceManager.GetString("Pattern_Ref", resourceCulture);
            }
        }
    }
}
