//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chiffon {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_Views {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_Views() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chiffon.Strings_Views", typeof(Strings_Views).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saisissez votre agence.
        /// </summary>
        internal static string CompanyName_Required {
            get {
                return ResourceManager.GetString("CompanyName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saisissez au moins 2 caractères.
        /// </summary>
        internal static string CompanyName_StringLength {
            get {
                return ResourceManager.GetString("CompanyName_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saisissez un email valide.
        /// </summary>
        internal static string Email_DataType {
            get {
                return ResourceManager.GetString("Email_DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saisissez votre email.
        /// </summary>
        internal static string Email_Required {
            get {
                return ResourceManager.GetString("Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saisissez au moins 5 caractères.
        /// </summary>
        internal static string Email_StringLength {
            get {
                return ResourceManager.GetString("Email_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saisissez votre prénom.
        /// </summary>
        internal static string FirstName_Required {
            get {
                return ResourceManager.GetString("FirstName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saisissez au moins 2 caractères.
        /// </summary>
        internal static string FirstName_StringLength {
            get {
                return ResourceManager.GetString("FirstName_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saisissez votre nom.
        /// </summary>
        internal static string LastName_Required {
            get {
                return ResourceManager.GetString("LastName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saisissez au moins 2 caractères.
        /// </summary>
        internal static string LastName_StringLength {
            get {
                return ResourceManager.GetString("LastName_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saisissez votre message.
        /// </summary>
        internal static string Message_Required {
            get {
                return ResourceManager.GetString("Message_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saisissez au moins 10 caractères.
        /// </summary>
        internal static string Message_StringLength {
            get {
                return ResourceManager.GetString("Message_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saisissez votre nom.
        /// </summary>
        internal static string Name_Required {
            get {
                return ResourceManager.GetString("Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saisissez au moins 2 caractères.
        /// </summary>
        internal static string Name_StringLength {
            get {
                return ResourceManager.GetString("Name_StringLength", resourceCulture);
            }
        }
    }
}
