//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chiffon.Properties
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chiffon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///Nouveau message de &lt;Message.EmailAddress.DisplayName&gt; (&lt;Message.EmailAddress.Address&gt;) :
        ///
        ///
        ///&lt;Message.MessageContent&gt;
        ///
        ///
        ///NB : Ce mail vous est envoyé automatiquement à partir de la page contact du site.
        ///
        ///.
        /// </summary>
        internal static string NewContactNotificationBody {
            get {
                return ResourceManager.GetString("NewContactNotificationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///Un nouveau membre vient de s&apos;inscrire : &lt;Message.EmailAddress.DisplayName&gt;
        ///
        ///
        ///Agence : &lt;Message.CompanyName&gt;
        ///Email : &lt;Message.EmailAddress.Address&gt;
        ///
        ///
        ///NB : Ce mail vous est envoyé automatiquement après toute nouvelle inscription.
        ///
        ///.
        /// </summary>
        internal static string NewMemberNotificationBody {
            get {
                return ResourceManager.GetString("NewMemberNotificationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///Bienvenue &lt;Message.EmailAddress.DisplayName&gt;,
        ///
        ///
        ///Les Simone vous remercient de l&apos;intérêt que vous avez souhaité leur accorder.
        ///
        ///Votre compte est activé.
        ///
        ///Votre identifiant : &lt;Message.EmailAddress.Address&gt;
        ///Votre mot de passe : &lt;Message.Password&gt;
        ///
        ///Je feuillette le portfolio : &lt;SiteUrl&gt;
        ///
        ///
        ///À très bientôt,
        ///
        ///Les Simone
        ///
        ///.
        /// </summary>
        internal static string WelcomeMailBody {
            get {
                return ResourceManager.GetString("WelcomeMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///Welcome &lt;Message.EmailAddress.DisplayName&gt;,
        ///
        ///
        ///Many thanks for your interest in the Simone project.
        ///
        ///Your login: &lt;Message.EmailAddress.Address&gt;
        ///Your password: &lt;Message.Password&gt;
        ///
        ///Browse the gallery: &lt;SiteUrl&gt;
        ///
        ///
        ///See you soon !
        ///
        ///Les Simone
        ///
        ///.
        /// </summary>
        internal static string WelcomeMailBody_English {
            get {
                return ResourceManager.GetString("WelcomeMailBody_English", resourceCulture);
            }
        }
    }
}
