//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18408
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chiffon.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chiffon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 
        ///
        ///Nouveau message de &lt;Message.ContactAddress.DisplayName&gt; (&lt;Message.ContactAddress.Address&gt;) :
        ///
        ///
        ///&lt;Message.Content&gt;
        ///
        ///
        ///NB : Ce mail vous est envoyé automatiquement à partir de la page contact du site.
        ///
        ///.
        /// </summary>
        internal static string NewContactNotificationBody {
            get {
                return ResourceManager.GetString("NewContactNotificationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 
        ///
        ///Un nouveau membre vient de s&apos;inscrire : &lt;Message.MemberAddress.DisplayName&gt;
        ///
        ///
        ///Agence : &lt;Message.CompanyName&gt;
        ///Email : &lt;Message.MemberAddress.Address&gt;
        ///
        ///
        ///NB : Ce mail vous est envoyé automatiquement après toute nouvelle inscription.
        ///
        ///.
        /// </summary>
        internal static string NewMemberNotificationBody {
            get {
                return ResourceManager.GetString("NewMemberNotificationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 
        ///
        ///Les Simone vous remercient de l&apos;intérêt que vous avez souhaité leur accorder.
        ///
        ///Votre compte est activé.
        ///
        ///Votre identifiant : @Html.Raw(ViewBag.Email)
        ///Votre mot de passe : @Html.Raw(ViewBag.Password)
        ///
        ///Je feuillette le portfolio : @Html.Raw(ViewBag.SiteUrl)
        ///
        ///.
        /// </summary>
        internal static string WelcomeMailBody {
            get {
                return ResourceManager.GetString("WelcomeMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 
        ///
        ///Welcome,
        ///
        ///Many thanks for your interest in the Simone project.
        ///
        ///Your login: @Html.Raw(ViewBag.Email)
        ///Your password: @Html.Raw(ViewBag.Password)
        ///
        ///Browse the gallery: @Html.Raw(ViewBag.SiteUrl)
        ///
        ///.
        /// </summary>
        internal static string WelcomeMailBody_English {
            get {
                return ResourceManager.GetString("WelcomeMailBody_English", resourceCulture);
            }
        }
    }
}
