//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chiffon.ViewModels.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chiffon.ViewModels.Resources.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisissez votre agence.
        /// </summary>
        internal static string CompanyName_Required {
            get {
                return ResourceManager.GetString("CompanyName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisissez au moins 2 caractères.
        /// </summary>
        internal static string CompanyName_StringLength {
            get {
                return ResourceManager.GetString("CompanyName_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisissez un email valide.
        /// </summary>
        internal static string Email_DataType {
            get {
                return ResourceManager.GetString("Email_DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisissez votre email.
        /// </summary>
        internal static string Email_Required {
            get {
                return ResourceManager.GetString("Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisissez au moins 5 caractères.
        /// </summary>
        internal static string Email_StringLength {
            get {
                return ResourceManager.GetString("Email_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisissez votre prénom.
        /// </summary>
        internal static string FirstName_Required {
            get {
                return ResourceManager.GetString("FirstName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisissez au moins 2 caractères.
        /// </summary>
        internal static string FirstName_StringLength {
            get {
                return ResourceManager.GetString("FirstName_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisissez votre nom.
        /// </summary>
        internal static string LastName_Required {
            get {
                return ResourceManager.GetString("LastName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisissez au moins 2 caractères.
        /// </summary>
        internal static string LastName_StringLength {
            get {
                return ResourceManager.GetString("LastName_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisissez votre message.
        /// </summary>
        internal static string Message_Required {
            get {
                return ResourceManager.GetString("Message_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisissez au moins 10 caractères.
        /// </summary>
        internal static string Message_StringLength {
            get {
                return ResourceManager.GetString("Message_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisissez votre nom.
        /// </summary>
        internal static string Name_Required {
            get {
                return ResourceManager.GetString("Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisissez au moins 2 caractères.
        /// </summary>
        internal static string Name_StringLength {
            get {
                return ResourceManager.GetString("Name_StringLength", resourceCulture);
            }
        }
    }
}
